use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// L7: A proactive suggestion generated by the assistant's Thought Queue.
#[derive(Debug, Clone, FromRow, Serialize, Deserialize)]
pub struct Thought {
    pub id: Uuid,
    pub user_id: Uuid,

    pub title: String,
    pub detail: Option<String>,
    pub reason: Option<String>,

    /// 0.0-1.0 confidence score
    pub confidence: f32,

    /// Memories that support this suggestion
    pub source_memory_ids: Vec<Uuid>,

    /// Whether user confirmation is required before acting
    pub requires_confirmation: bool,

    /// Lifecycle status
    pub status: ThoughtStatus,

    /// When to surface this thought
    pub scheduled_at: Option<DateTime<Utc>>,

    /// When the user acted on it
    pub resolved_at: Option<DateTime<Utc>>,

    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "VARCHAR")]
pub enum ThoughtStatus {
    #[sqlx(rename = "pending")]
    Pending,
    #[sqlx(rename = "shown")]
    Shown,
    #[sqlx(rename = "confirmed")]
    Confirmed,
    #[sqlx(rename = "dismissed")]
    Dismissed,
    #[sqlx(rename = "expired")]
    Expired,
}

impl ThoughtStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Shown => "shown",
            Self::Confirmed => "confirmed",
            Self::Dismissed => "dismissed",
            Self::Expired => "expired",
        }
    }
}
