use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::FromRow;
use uuid::Uuid;

/// L7: A proactive suggestion generated by the assistant's Thought Queue.
#[derive(Debug, Clone, FromRow, Serialize, Deserialize)]
pub struct Thought {
    pub id: Uuid,
    pub user_id: Uuid,

    pub title: String,
    pub detail: Option<String>,
    pub reason: Option<String>,

    /// 0.0-1.0 confidence score
    pub confidence: f32,

    /// Memories that support this suggestion
    pub source_memory_ids: Vec<Uuid>,

    /// Whether user confirmation is required before acting
    pub requires_confirmation: bool,

    /// Lifecycle status
    pub status: ThoughtStatus,

    /// When the thought was first shown to the user
    pub shown_at: Option<DateTime<Utc>>,

    /// When to surface this thought (NULL = immediate; future = snoozed)
    pub scheduled_at: Option<DateTime<Utc>>,

    /// When the user acted on it (terminal states only: accepted / dismissed)
    pub resolved_at: Option<DateTime<Utc>>,

    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

/// Thought Queue lifecycle state machine:
///
/// ```text
/// pending ─→ shown ──→ accepted   (terminal, resolved_at = NOW)
///    │         │   ╰─→ dismissed   (terminal, resolved_at = NOW)
///    │         │   ╰─→ snoozed     (non-terminal, scheduled_at = NOW+3d)
///    │         ╰─→ accepted | dismissed | snoozed  (direct, skipping shown)
///    │
///    ╰─→ expired   (system-only: stale pending after STALE_THOUGHT_DAYS)
///
/// snoozed ─→ pending   (system-only: scheduled_at reached, maintenance sweep)
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "VARCHAR")]
pub enum ThoughtStatus {
    #[sqlx(rename = "pending")]
    Pending,
    #[sqlx(rename = "shown")]
    Shown,
    #[sqlx(rename = "accepted")]
    Accepted,
    #[sqlx(rename = "dismissed")]
    Dismissed,
    #[sqlx(rename = "snoozed")]
    Snoozed,
    #[sqlx(rename = "expired")]
    Expired,
}

impl ThoughtStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Shown => "shown",
            Self::Accepted => "accepted",
            Self::Dismissed => "dismissed",
            Self::Snoozed => "snoozed",
            Self::Expired => "expired",
        }
    }
}
