services:
  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: poc_age
      POSTGRES_USER: poc
      POSTGRES_PASSWORD: poc
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poc"]
      interval: 5s
      timeout: 3s
      retries: 5
